apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: jayjs/py-test-repo:python-helloworld-v1.0.0
        imagePullPolicy: IfNotPresent
        name: python-helloworld      
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
